version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # Ensure the node version matches your local environment
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Clean npm cache
          command: npm cache clean --force  # Ensure clean cache
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps  # Add --legacy-peer-deps if there are dependency issues
      - run:
          name: Verify package installation
          command: npm list --depth=0  # Verify that all packages are installed correctly

  run_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Jest tests
          command: npx jest --verbose  # Run jest with verbose to capture more logs

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Deploy Lambda (optional)
          command: |
            echo "Deploying Lambda..."

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - run_tests
