version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:23.3.0

jobs:
  run_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run Jest tests
          command: |
            npm test

  deploy:
    docker:
      - image: cimg/node:23.3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Install Serverless Framework
          command: |
            npm install serverless
      - run:
          name: Deploy Lambda using Serverless
          command: |
            export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY
            npx serverless deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - run_tests
      - deploy:
          requires:
            - run_tests
          filters:
            branches:
              only: feature/deploy
