version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18

jobs:
  run_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run Jest tests
          command: |
            npm test

  deploy:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Install Serverless Framework
          command: |
            npm install serverless
      - run:
          name: Deploy Lambda using Serverless
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_REGION=$AWS_REGION
            npx serverless deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - run_tests
      - deploy:
          requires:
            - run_tests
          filters:
            branches:
              only: feature/deploy 