version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16 # Choose the Node.js Docker image version that matches your project

jobs:
  run_tests:
    executor: node-executor
    steps:
      - checkout # Checks out the code from your repository
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run Jest tests
          command: |
            npm test

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Install Serverless Framework
          command: |
            npm install -g serverless
      - run:
          name: Deploy Lambda using Serverless
          command: |
            # Set up AWS credentials (ensure these are set as environment variables in CircleCI)
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_REGION=$AWS_REGION
            # Deploy Lambda function using Serverless
            serverless deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - run_tests
      - deploy:
          requires:
            - run_tests
          filters:
            branches:
              only: main  # Only deploy on the 'main' branch
